In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import plotly.offline as pyo
import plotly.express as px

In [14]:
df0 = pd.read_csv('KS_WNTY_PUBLIC_PHSTRN_FCLTY_STTUS_202110 (1).csv')
df0

,FACI_NM,FACI_GB_CD,FACI_GB_NM,FCOB_CD,FCOB_NM,FTYPE_CD,FTYPE_NM,FMNG_TYPE_GB_CD,FMNG_TYPE_GB_NM,FMNG_CP_CD,...,FACI_ROAD_ADDR1,FACI_POINT_X,FACI_POINT_Y,TOT_FACI_AREA,STAND_CPT_PSN_CNT,STAND_SEAT_CNT,FACI_HOMEPAGE,NATION_YN,FACI_STAT,DEL_YN
0,(외립석입구),P,공공,P08,간이운동장,P0801,간이운동장,1.0,지방자치단체,4.700000e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,0,N
1,(자산경로당),P,공공,P08,간이운동장,P0801,간이운동장,1.0,지방자치단체,4.700000e+09,...,경상북도 김천시 자산3길 16 (성내동),128.122092,36.120771,NaN,NaN,NaN,NaN,N,0,N
2,신리 봉계초등학교 (강당뒤),P,공공,P08,간이운동장,P0801,간이운동장,1.0,지방자치단체,4.700000e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,0,N
3,신리 봉계초등학교 (강당뒤),P,공공,P08,간이운동장,P0801,간이운동장,1.0,지방자치단체,4.700000e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,0,Y
4,성당뒤,P,공공,P08,간이운동장,P0801,간이운동장,1.0,지방자치단체,4.700000e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,0,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29784,판교공원 X-Game장,P,공공,P08,간이운동장,P0801,간이운동장,1.0,지방자치단체,4.100000e+09,...,경기도 성남시 분당구 운중로225번길 37 (판교동),127.097822,37.395369,NaN,NaN,NaN,NaN,N,0,N
29785,용인시여성회관YMCA스포츠센타,P,공공,P09,체육관,P0903,생활체육관,1.0,지방자치단체,4.100000e+09,...,경기도 용인시 수지구 문정로7번길 15 (풍덕천동),127.095500,37.320524,1322.0,NaN,NaN,http:/www.yonginymca.or.kr/,N,0,N
29786,용인시여성회관YMCA스포츠센터,P,공공,P09,체육관,P0903,생활체육관,1.0,지방자치단체,4.100000e+09,...,경기도 용인시 수지구 문정로7번길 15 (풍덕천동),127.095500,37.320524,NaN,NaN,NaN,http://www.yonginymca.or.kr,N,0,Y
29787,용인시여성회관YMCA스포츠센터수영장,P,공공,P11,수영장,P1101,수영장,1.0,지방자치단체,4.100000e+09,...,경기도 용인시 수지구 문정로7번길 15 (풍덕천동),127.095500,37.320524,NaN,NaN,NaN,http://www.yonginsports.com/icarusx/erp.php?ST...,N,0,N
29788,기(岐)암리 동네체육시설,P,공공,P08,간이운동장,P0801,간이운동장,1.0,지방자치단체,4.300000e+09,...,충청북도 청주시 상당구 미원면 기암구말길 73-15,127.698832,36.686969,NaN,NaN,NaN,NaN,N,0,N

In [15]:
df = df0[['FACI_NM', 'FTYPE_NM', 'FACI_ROAD_ADDR1', 'FACI_POINT_X', 'FACI_POINT_Y', 'FACI_STAT', 'DEL_YN']]
df

,FACI_NM,FTYPE_NM,FACI_ROAD_ADDR1,FACI_POINT_X,FACI_POINT_Y,FACI_STAT,DEL_YN
0,(외립석입구),간이운동장,NaN,NaN,NaN,0,N
1,(자산경로당),간이운동장,경상북도 김천시 자산3길 16 (성내동),128.122092,36.120771,0,N
2,신리 봉계초등학교 (강당뒤),간이운동장,NaN,NaN,NaN,0,N
3,신리 봉계초등학교 (강당뒤),간이운동장,NaN,NaN,NaN,0,Y
4,성당뒤,간이운동장,NaN,NaN,NaN,0,Y
...,...,...,...,...,...,...,...
29784,판교공원 X-Game장,간이운동장,경기도 성남시 분당구 운중로225번길 37 (판교동),127.097822,37.395369,0,N
29785,용인시여성회관YMCA스포츠센타,생활체육관,경기도 용인시 수지구 문정로7번길 15 (풍덕천동),127.095500,37.320524,0,N
29786,용인시여성회관YMCA스포츠센터,생활체육관,경기도 용인시 수지구 문정로7번길 15 (풍덕천동),127.095500,37.320524,0,Y
29787,용인시여성회관YMCA스포츠센터수영장,수영장,경기도 용인시 수지구 문정로7번길 15 (풍덕천동),127.095500,37.320524,0,N
29788,기(岐)암리 동네체육시설,간이운동장,충청북도 청주시 상당구 미원면 기암구말길 73-15,127.698832,36.686969,0,N

In [16]:
df.isnull().sum()

FACI_NM                0
FTYPE_NM               0
FACI_ROAD_ADDR1    11897
FACI_POINT_X        3442
FACI_POINT_Y        3442
FACI_STAT              0
DEL_YN                 0
dtype: int64

운동 추천 -> 실내/실외, 운동종목,

In [19]:
a = df[df.FACI_STAT == 99].index
df = df.drop(a)
df

,FACI_NM,FTYPE_NM,FACI_ROAD_ADDR1,FACI_POINT_X,FACI_POINT_Y,FACI_STAT,DEL_YN
0,(외립석입구),간이운동장,NaN,NaN,NaN,0,N
1,(자산경로당),간이운동장,경상북도 김천시 자산3길 16 (성내동),128.122092,36.120771,0,N
2,신리 봉계초등학교 (강당뒤),간이운동장,NaN,NaN,NaN,0,N
3,신리 봉계초등학교 (강당뒤),간이운동장,NaN,NaN,NaN,0,Y
4,성당뒤,간이운동장,NaN,NaN,NaN,0,Y
...,...,...,...,...,...,...,...
29784,판교공원 X-Game장,간이운동장,경기도 성남시 분당구 운중로225번길 37 (판교동),127.097822,37.395369,0,N
29785,용인시여성회관YMCA스포츠센타,생활체육관,경기도 용인시 수지구 문정로7번길 15 (풍덕천동),127.095500,37.320524,0,N
29786,용인시여성회관YMCA스포츠센터,생활체육관,경기도 용인시 수지구 문정로7번길 15 (풍덕천동),127.095500,37.320524,0,Y
29787,용인시여성회관YMCA스포츠센터수영장,수영장,경기도 용인시 수지구 문정로7번길 15 (풍덕천동),127.095500,37.320524,0,N
29788,기(岐)암리 동네체육시설,간이운동장,충청북도 청주시 상당구 미원면 기암구말길 73-15,127.698832,36.686969,0,N

In [20]:
a = df[df.DEL_YN == 'Y'].index
df = df.drop(a)
df

,FACI_NM,FTYPE_NM,FACI_ROAD_ADDR1,FACI_POINT_X,FACI_POINT_Y,FACI_STAT,DEL_YN
0,(외립석입구),간이운동장,NaN,NaN,NaN,0,N
1,(자산경로당),간이운동장,경상북도 김천시 자산3길 16 (성내동),128.122092,36.120771,0,N
2,신리 봉계초등학교 (강당뒤),간이운동장,NaN,NaN,NaN,0,N
5,개나리 공원 야외운동기구,간이운동장,경상북도 문경시 시청2길 21 (모전동),128.187963,36.586970,0,N
6,남산리 족구장,간이운동장,NaN,NaN,NaN,0,N
...,...,...,...,...,...,...,...
29782,X-게임장,기타시설,대구광역시 동구 금호강변로 278 (율하동),128.692840,35.859924,0,N
29784,판교공원 X-Game장,간이운동장,경기도 성남시 분당구 운중로225번길 37 (판교동),127.097822,37.395369,0,N
29785,용인시여성회관YMCA스포츠센타,생활체육관,경기도 용인시 수지구 문정로7번길 15 (풍덕천동),127.095500,37.320524,0,N
29787,용인시여성회관YMCA스포츠센터수영장,수영장,경기도 용인시 수지구 문정로7번길 15 (풍덕천동),127.095500,37.320524,0,N
29788,기(岐)암리 동네체육시설,간이운동장,충청북도 청주시 상당구 미원면 기암구말길 73-15,127.698832,36.686969,0,N

In [21]:
index1 = df[['FACI_POINT_X', 'FACI_POINT_Y']].dropna(axis=0).index
df = df.loc[index1]
df

,FACI_NM,FTYPE_NM,FACI_ROAD_ADDR1,FACI_POINT_X,FACI_POINT_Y,FACI_STAT,DEL_YN
1,(자산경로당),간이운동장,경상북도 김천시 자산3길 16 (성내동),128.122092,36.120771,0,N
5,개나리 공원 야외운동기구,간이운동장,경상북도 문경시 시청2길 21 (모전동),128.187963,36.586970,0,N
11,차탄리 노인회관 뒤,간이운동장,경기도 연천군 연천읍 차현로 92,127.076813,38.099404,0,N
12,어룡동 소촌마을 동네체육시설,간이운동장,NaN,126.794461,35.145440,0,N
14,국당마을 소공원,간이운동장,경상북도 경주시 황남동 483-3,129.210528,35.827046,0,N
...,...,...,...,...,...,...,...
29782,X-게임장,기타시설,대구광역시 동구 금호강변로 278 (율하동),128.692840,35.859924,0,N
29784,판교공원 X-Game장,간이운동장,경기도 성남시 분당구 운중로225번길 37 (판교동),127.097822,37.395369,0,N
29785,용인시여성회관YMCA스포츠센타,생활체육관,경기도 용인시 수지구 문정로7번길 15 (풍덕천동),127.095500,37.320524,0,N
29787,용인시여성회관YMCA스포츠센터수영장,수영장,경기도 용인시 수지구 문정로7번길 15 (풍덕천동),127.095500,37.320524,0,N
29788,기(岐)암리 동네체육시설,간이운동장,충청북도 청주시 상당구 미원면 기암구말길 73-15,127.698832,36.686969,0,N

In [23]:
df = df.drop(['FACI_STAT', 'DEL_YN'], axis=1)

KeyError: "['FACI_STAT' 'DEL_YN'] not found in axis"

In [27]:
index1 = df[['FACI_ROAD_ADDR1']].dropna(axis=0).index
df = df.loc[index1]
df

,FACI_NM,FTYPE_NM,FACI_ROAD_ADDR1,FACI_POINT_X,FACI_POINT_Y
1,(자산경로당),간이운동장,경상북도 김천시 자산3길 16 (성내동),128.122092,36.120771
5,개나리 공원 야외운동기구,간이운동장,경상북도 문경시 시청2길 21 (모전동),128.187963,36.586970
11,차탄리 노인회관 뒤,간이운동장,경기도 연천군 연천읍 차현로 92,127.076813,38.099404
14,국당마을 소공원,간이운동장,경상북도 경주시 황남동 483-3,129.210528,35.827046
15,장미공원 야외운동기구,간이운동장,경북 문경시 모전동 865-4,128.189231,36.585440
...,...,...,...,...,...
29782,X-게임장,기타시설,대구광역시 동구 금호강변로 278 (율하동),128.692840,35.859924
29784,판교공원 X-Game장,간이운동장,경기도 성남시 분당구 운중로225번길 37 (판교동),127.097822,37.395369
29785,용인시여성회관YMCA스포츠센타,생활체육관,경기도 용인시 수지구 문정로7번길 15 (풍덕천동),127.095500,37.320524
29787,용인시여성회관YMCA스포츠센터수영장,수영장,경기도 용인시 수지구 문정로7번길 15 (풍덕천동),127.095500,37.320524
29788,기(岐)암리 동네체육시설,간이운동장,충청북도 청주시 상당구 미원면 기암구말길 73-15,127.698832,36.686969

In [28]:
df.isnull().sum()

FACI_NM            0
FTYPE_NM           0
FACI_ROAD_ADDR1    0
FACI_POINT_X       0
FACI_POINT_Y       0
dtype: int64

In [8]:
df.columns = ['name', 'sports', 'addr', 'x-coord', 'y-coord', 'tel']

In [29]:
df.to_csv('map_sports_new_cp.csv', encoding='cp949')

In [26]:
df.to_csv('map_sports.csv')